const cupoCata = 5;
const inscritos = 8;

//if condicional de si (si cupo cata es mayor a inscrito)

if (cupoCata > inscritos) {
    console.log("Hay cupos, abrir reserva");
} else { 
    console.log("Cata llena, ofrecer lista de espera");
}


//else es de lo contrario



//condiciones de comparacion:
8 > 5  // true mayor que
3 < 10  // true menor que
8 >= 8  //true mayor o igual que
4 <= 9  // true menor o igual que
5 === 5  // true igual que
5 !== 3  //true   diferente de



//////////////////////////////

const maxTazasespeciales = 3;


if (maxTazasespeciales > 2) {
    console.log("Ya tienes el Numero maximo de tasas reservadas")
} else {
    console.log("Su reserva a sido anotada")
}
